# Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
import pandas as pd

In [2]:
first_matrix=np.array([[2,3,4],[3,4,5],[4,5,6]])
second_matrix=np.array([[3,5,6],[7,6,4],[9,6,4]])


In [3]:
first_matrix

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [4]:
second_matrix

array([[3, 5, 6],
       [7, 6, 4],
       [9, 6, 4]])

In [5]:
#add two matrix
first_matrix+second_matrix

array([[ 5,  8, 10],
       [10, 10,  9],
       [13, 11, 10]])

# Write a Python Program to Multiply Two Matrices?

In [6]:
first_matrix=np.array([[2,3,4],[3,4,5],[4,5,6]])
second_matrix=np.array([[3,5,6],[7,6,4],[9,6,4]])

In [8]:
first_matrix

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
second_matrix

array([[3, 5, 6],
       [7, 6, 4],
       [9, 6, 4]])

In [9]:
# multiply two matrix
first_matrix*second_matrix

array([[ 6, 15, 24],
       [21, 24, 20],
       [36, 30, 24]])

# Write a Python Program to Transpose a Matrix?

In [14]:
second_matrix

array([[3, 5, 6],
       [7, 6, 4],
       [9, 6, 4]])

In [16]:
second_matrix.T

array([[3, 7, 9],
       [5, 6, 6],
       [6, 4, 4]])

# Write a Python Program to Sort Words in Alphabetic Order?

In [26]:
# Program to sort alphabetically the words form a string provided by the user
 
# take input from the user
my_str = input("Enter a string: ")
 
# breakdown the string into a list of words
words = my_str.split()
 
# sort the list
words.sort()

 
# display the sorted words
  
for word in words:
    
    print(word)


Enter a string: "rose is the best flower in the world"
"rose
best
flower
in
is
the
the
world"


# Write a Python Program to Remove Punctuation From a String?

In [12]:
import string

In [20]:
punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~''' 
# take input from the user  
my_str = input("Enter a string: ") 
# remove punctuation from the string  
no_punct = "" 
for char in my_str:
    if char not in punctuation:
        no_punct = no_punct + char  
# display the unpunctuated string
print(no_punct)  


Enter a string: "tisdghhjfr#$#@gg..,,,,,"
tisdghhjfrgg
